Also test on clients and send email on a triggered build
datalad/git-annex pull request #152
Opened 2023-02-10 15:58 UTC by yarikoptic

I've not tried.  Might need a thoroughly careful review ;)

2023-02-10 16:15 UTC, jwodder requested changes

2023-02-10 16:15 UTC, jwodder commented on .github/workflows/template/build-{{ostype}}.yaml.j2
>        - name: Send e-mail on failed scheduled run
```suggestion
      - name: Send e-mail on failed run
```

2023-02-10 16:15 UTC, jwodder commented on .github/workflows/template/build-{{ostype}}.yaml.j2
>        - name: Send e-mail on failed scheduled run
```suggestion
      - name: Send e-mail on failed run
```

2023-02-10 16:16 UTC, jwodder commented
This change is also needed:

```diff
diff --git a/.github/workflows/tools/daily-status.py b/.github/workflows/tools/daily-status.py
index c21da03d0e..a98d571013 100644
--- a/.github/workflows/tools/daily-status.py
+++ b/.github/workflows/tools/daily-status.py
@@ -166,7 +166,7 @@ def main():
         for wfname in WORKFLOWS:
             wf = wfrepo.get_workflow(wfname)
             for run in wf.get_runs():
-                if run.status != "completed" or run.event != "schedule":
+                if run.status != "completed" or run.event not in ("schedule", "workflow_dispatch"):
                     continue
                 dt = ensure_aware(run.created_at)
                 if dt <= cutoff:
```

2023-02-15 16:47 UTC, yarikoptic commented
all good now @jwodder ?

2023-02-16 02:39 UTC, merged